# Generated by Django 4.2 on 2023-04-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titutlo', models.CharField(max_length=50, null=True)),
                ('orden', models.IntegerField(null=True)),
                ('descripcion', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titutlo', models.CharField(max_length=50, null=True)),
                ('orden', models.IntegerField(null=True)),
                ('descripcion', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titutlo', models.CharField(max_length=50, null=True)),
                ('orden', models.IntegerField(null=True)),
                ('descripcion', models.CharField(max_length=1024, null=True)),
            ],
        ),
    ]
