# Generated by Django 4.2 on 2023-05-03 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notnetflix', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='titutlo',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='titutlo',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='serie',
            old_name='titutlo',
            new_name='titulo',
        ),
    ]
